### ISSUE TITLE
Database structure and integrity

### ISSUE THREAD

**Issue by simon-brooke** [simon-brooke/youyesyet#4]

**Comment by jamiehollern** [comment]
Does this issue cover backups and failover? How often will backups be taken? Full nightly backup with hourly differential backup? How easy is it to de-pollute records over a certain time frame?

**Comment by simon-brooke** [comment]
Good questions to which I don't yet have an answer. This relates to the issue of sharding. If we have to shard (and I think we will) then not only must each shard have its own backup and replication system but also we need some way to integrate the data from the shards at the back end for analysis. This is discussed in the [scaling document](https://github.com/simon-brooke/youyesyet/blob/master/doc/specification/scaling.md).

All these issues are related to this epic but someone needs to split them down into manageable tasks and create issues for them.

I'm also entirely comfortable for someone else to take on responsibility both for the scaling and for the backup and integration issues. You fancy taking that on - at a specification level, if not necessarily a coding one?
